---
title: Smartia.Com.Br
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: My Jekyll Website

# Staticman
staticman:
 allowedFields: ['name', 'email', 'comment']
 branch: master
 commitMessage: "New comment added"
 filename: "entry{@timestamp}"
 format: yml
 moderation: true
 path: "_data/reviews"
 requiredFields: ['name', 'email', 'comment']